In [26]:
import cv2
import os
import numpy as np
import pickle

In [22]:
data_path = "./data/"
people = os.listdir(data_path)

print(people)

labels = []
caras = []

label = 1

for folder in people:
    person_path = data_path + '/' + folder
    print('Leyendo las imágenes de la carpeta...{}'.format(folder))

    for imagen in os.listdir(person_path):
        # print('Caras: ', folder + '/' + imagen)
        labels.append(label)
        caras.append(cv2.imread(person_path + '/' + imagen,0)) #el 0 es el que indica la escala de grises, que es el formato aceptado en el entrenamiento
print('Imágenes pasadas a arrays')

caras_norm = []
for cara in caras:
    caras_norm.append(cara/255)

print(caras_norm)



['Fran', 'Kike', 'Mario', 'Nani', 'Ouissam', 'Selu']
Leyendo las imágenes de la carpeta...Fran
Leyendo las imágenes de la carpeta...Kike
Leyendo las imágenes de la carpeta...Mario
Leyendo las imágenes de la carpeta...Nani
Leyendo las imágenes de la carpeta...Ouissam
Leyendo las imágenes de la carpeta...Selu
Imágenes pasadas a arrays
[array([[0.65098039, 0.7254902 , 0.70588235, ..., 0.84313725, 0.87058824,
        0.81176471],
       [0.71372549, 0.75294118, 0.69803922, ..., 0.78039216, 0.84313725,
        0.84313725],
       [0.72156863, 0.74901961, 0.71764706, ..., 0.88235294, 0.90196078,
        0.80392157],
       ...,
       [0.60784314, 0.58039216, 0.61176471, ..., 0.85098039, 0.8627451 ,
        0.83921569],
       [0.67058824, 0.62352941, 0.58431373, ..., 0.76470588, 0.8       ,
        0.80392157],
       [0.6745098 , 0.57647059, 0.61960784, ..., 0.79215686, 0.89803922,
        0.79215686]]), array([[0.69019608, 0.70588235, 0.70588235, ..., 0.80392157, 0.83137255,
        0.854

In [ ]:
with open('outfile', 'wb') as fp:
    pickle.dump(itemlist, fp)

In [13]:
np.count_nonzero(labels)

1800

In [15]:
caras

[array([[166, 185, 180, ..., 215, 222, 207],
        [182, 192, 178, ..., 199, 215, 215],
        [184, 191, 183, ..., 225, 230, 205],
        ...,
        [155, 148, 156, ..., 217, 220, 214],
        [171, 159, 149, ..., 195, 204, 205],
        [172, 147, 158, ..., 202, 229, 202]], dtype=uint8),
 array([[176, 180, 180, ..., 205, 212, 218],
        [187, 177, 168, ..., 218, 222, 223],
        [181, 195, 177, ..., 223, 224, 232],
        ...,
        [152, 145, 164, ..., 173, 204, 226],
        [152, 155, 161, ..., 200, 203, 223],
        [155, 136, 170, ..., 199, 193, 195]], dtype=uint8),
 array([[174, 182, 178, ..., 212, 228, 193],
        [185, 175, 176, ..., 228, 215, 200],
        [180, 194, 171, ..., 230, 208, 207],
        ...,
        [150, 153, 158, ..., 215, 213, 217],
        [142, 154, 154, ..., 218, 211, 216],
        [152, 151, 148, ..., 203, 202, 208]], dtype=uint8),
 array([[213, 210, 211, ..., 236, 235, 236],
        [211, 212, 214, ..., 237, 234, 233],
        [206, 20

In [25]:
print(caras_norm.shape)



AttributeError: 'list' object has no attribute 'shape'